### ISSUE TITLE
"undefined" error every time I try to run Autotuneweb

### ISSUE THREAD

**Issue by idowolf** [MarkMpn/AutotuneWeb#30]
I get this error every time I try to run the webapp, not sure what other details I should give but hopefully the logs will be helpful enough :) Thanks for your help!

```
Compressing old json and log files to save space...
gzip: ns-*.json: No such file or directory
gzip: autotune*.json: No such file or directory
Autotune disk usage:
16K	.
Overall disk used/avail:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1        69G   53M   65G   1% /mnt
Grabbing NIGHTSCOUT treatments.json and entries/sgv.json for date range...
Query: https://ido-cgm.herokuapp.com entries/sgv.json find%5Bdate%5D%5B%24gte%5D=1608170400000&find%5Bdate%5D%5B%24lte%5D=1608256800000&count=1500
-rw-r--r-- 1 _azbatch _azbatchgrp 3 Dec 24 13:05 ns-entries.2020-12-17.json
Query: https://ido-cgm.herokuapp.com treatments.json find%5Bcreated_at%5D%5B%24gte%5D=2020-12-16T06:00+02:00&find%5Bcreated_at%5D%5B%24lte%5D=2020-12-18T18:00+02:00
-rw-r--r-- 1 _azbatch _azbatchgrp 3 Dec 24 13:05 ns-treatments.2020-12-17.json
oref0-autotune-prep   ns-treatments.2020-12-17.json profile.json ns-entries.2020-12-17.json profile.pump.json > autotune.2020-12-17.json
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at categorizeBGDatums (/usr/src/oref0/lib/autotune-prep/categorize.js:73:28)
    at generate (/usr/src/oref0/lib/autotune-prep/index.js:23:30)
    at Object.<anonymous> (/usr/src/oref0/bin/oref0-autotune-prep.js:131:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
Warning: API_SECRET is not set when calling oref0-autotune.sh
(this is only a problem if you have locked down read-only access to your NS).
Could not run oref0-autotune-prep ns-treatments.2020-12-17.json profile.json ns-entries.2020-12-17.json
```

**Comment by idowolf** [comment]
Completely my bad, it was just that I was missing data in some of the days in my range. Thanks!
