### ISSUE TITLE
Autotune Error

### ISSUE THREAD

**Issue by sircsaba** [MarkMpn/AutotuneWeb#50]
I'm getting the email back with this error and it sends me the logs. The error message in the logs is :

Could not parse input data:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/usr/src/oref0/bin/oref0-autotune-prep.js:63:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
oref0-autotune-core autotune.2024-03-21.json profile.json profile.pump.json > newprofile.2024-03-21.json
/usr/src/oref0/lib/autotune/index.js:151
    CRData.forEach(function(CRDatum) {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at tuneAllTheThings (/usr/src/oref0/lib/autotune/index.js:151:12)
    at Object.<anonymous> (/usr/src/oref0/bin/oref0-autotune-core.js:67:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
false
Warning: API_SECRET is not set when calling oref0-autotune.sh
(this is only a problem if you have locked down read-only access to your NS).
Could not run oref0-autotune-core autotune.2024-03-21.json profile.json profile.pump.json

**Comment by MarkMpn** [comment]
This normally indicates that you have a day without any glucose data in Nightscout. Please make sure you select a date range where you have readings for every day.

**Comment by sircsaba** [comment]
Hello,

Thanks for getting back to me.

I did a few times with different days which all have glucose reading ... Do
I need a minimum number of days or can I just do one day ? (Which I tried
but got an error ...)

**Comment by MarkMpn** [comment]
Can you share your Nightscout URL so I can look into it further?

**Comment by sircsaba** [comment]
Hello,

Here it is


http://nightscout-valerie.ddnsfree.com:3124/

Thanks

**Comment by MarkMpn** [comment]
From the log files I can see that Nightscout gives an empty result (probably returning an error but it’s not visible in the logs) when Autotune requested the list of treatments for one of the days in the selected time range.

This seems like an error is happening at the Nightscout end, you might be able to see more information in your web server logs but I’m afraid there’s nothing more I can see from here. I have been able to successfully run Autotune on this URL if I select to use only 2 or 3 days worth of data, but as soon as I go to 4 or more days I get this same error.

**Comment by sircsaba** [comment]
Hello,

Thank you !

Regards,
